name: simple-worm-scripts

channels:
  - conda-forge
  - pytorch

dependencies:
  - python = 3.12
  - fenics-dolfinx = 0.9
  - numpy >= 2.0
  - matplotlib
  - pytest
  - git
  - pip
  - pip:
      - git+https://gitlab.com/tom-ranner/simple-worm.git@master

